### PR TITLE
Bill rates

### PR DESCRIPTION
**Pull request by kevintdao**
## User Story

https://github.com/brandonegg/hospitality/issues/38

As an admin,
So that doctors can invoice patients for the services used,
I would like to create bill rates for those services.

## Acceptance

- [x] Create services/items with different types and cost amount
- [x] Provide description field for what the billable item is
- [x] Provide cost field for how much the service costs

## Summary of Changes

- Added rates page
- Added ability to create/edit/delete rate

## Noteworthy Mentions

Make sure the run `npm run db:push` to get the updated database schema and `npm run db:seed` to seed the newly created rates.

## Screenshots

Rates page
Screenshot 2023-04-16 at 8 50 57 PM

Create rate popup
Screenshot 2023-04-16 at 8 51 14 PM

Edit rate popup
Screenshot 2023-04-16 at 8 51 21 PM

Delete rate popup
Screenshot 2023-04-16 at 8 51 28 PM

### CODE REVIEW

**Review by brandonegg — COMMENTED** [review]
I'm curious what VS Code extension/additional linter you are using. The reason I ask, I agree with the formatting changes made but since there is no specific rules enforcing them in the repository it creates a lot of merge conflicts down the road for others. Is there anyway we can add what your formatting changes are doing to our linted?

**Comment by kevintdao** [comment]
> I'm curious what VS Code extension/additional linter you are using. The reason I ask, I agree with the formatting changes made but since there is no specific rules enforcing them in the repository it creates a lot of merge conflicts down the road for others. Is there anyway we can add what your formatting changes are doing to our linted?

I think most of these settings are from my VScode. I'm using `Prettier` from the `Prettier` extension as my default formatter.
Screenshot 2023-04-16 at 10 16 12 PM

I like to use tab size of 2 with the `Rainbow indent` extension. I think this you can add to the `prettier.config.cjs` file.
Screenshot 2023-04-16 at 10 17 26 PM

And I have FormatOnSave checked for vscode as well. That way, the file that I'm working on is automatically format for me when saved instead of running the lint command.
Screenshot 2023-04-16 at 10 19 11 PM

**Comment by brandonegg** [comment]
> > I'm curious what VS Code extension/additional linter you are using. The reason I ask, I agree with the formatting changes made but since there is no specific rules enforcing them in the repository it creates a lot of merge conflicts down the road for others. Is there anyway we can add what your formatting changes are doing to our linted?
> 
> I think most of these settings are from my VScode. I'm using `Prettier` from the `Prettier` extension as my default formatter. Screenshot 2023-04-16 at 10 16 12 PM
> 
> I like to use tab size of 2 with the `Rainbow indent` extension. I think this you can add to the `prettier.config.cjs` file. Screenshot 2023-04-16 at 10 17 26 PM
> 
> And I have FormatOnSave checked for vscode as well. That way, the file that I'm working on is automatically format for me when saved instead of running the lint command. Screenshot 2023-04-16 at 10 19 11 PM

@kevintdao perfect, thank you for sending this! I'll see if I can update the linter to match this

**Comment by kevintdao** [comment]
@brandonegg everything should be resolved now

**Review by brandonegg — APPROVED** [review]

**Comment by brandonegg** [comment]
> @brandonegg everything should be resolved now

Perfect, thank you!

**Pull request merged**
